# Generated by Django 3.1.1 on 2020-09-27 13:11

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(to='blog.BlogCategory'),
        ),
    ]
