# Generated by Django 3.1.1 on 2020-09-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200927_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='category',
            new_name='categories',
        ),
    ]
