# Generated by Django 3.1.1 on 2020-09-23 20:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flex',
            name='content',
            field=wagtail.core.fields.StreamField([('Title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Add your Text', required=True))]))], blank=True, null=True),
        ),
    ]
