# Generated by Django 3.1.1 on 2020-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasetting',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook url', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter url', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='youtube',
            field=models.URLField(blank=True, help_text='Youtube channel url', null=True),
        ),
    ]
